version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frankenphp_portal_data_bridging
    ports:
      - "8081:80"
    volumes:
      - /home/portal-data-bridging/public_html:/app
    environment:
      - FRANKENPHP_HTTP_PORT=80
      - FRANKENPHP_HTTPS_PORT=0