

version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3307
      - DB_DATABASE=intergrasi_portal
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
