services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frankenphp_portal_data_bridging
    ports:
      - "8082:80"
    volumes:
      - /home/portal-data-bridging/public_html2:/app
    environment:
      FRANKENPHP_HTTP_PORT: 80
      FRANKENPHP_HTTPS_PORT: 0
      FRANKENPHP_WORKERS: 4
      FRANKENPHP_BOOTSTRAP: public/index.php
