services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frankenphp_portal_data_bridging
    entrypoint: ["php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port=80", "--admin-port=2080"]
    ports:
      - "8082:80"
    volumes:
      - /home/portal-data-bridging/public_html:/app
    # environment:
    #   FRANKENPHP_HTTP_PORT: 80
    #   FRANKENPHP_HTTPS_PORT: 0
    #   FRANKENPHP_WORKERS: 4
    #   FRANKENPHP_BOOTSTRAP: public/index.php
    restart: unless-stopped